//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeIG.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Member
    {
        public System.Guid MemberID { get; set; }


        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [StringLength(50)]
        public string Account { get; set; }

        [DisplayName("密碼")]
        [Required]
        [StringLength(8, ErrorMessage = "密碼必須3-8字元", MinimumLength = 3)]
        public string Password { get; set; }

        [DisplayName("確認密碼")]
        [Compare("Password", ErrorMessage = "密碼不相同")]
        [Required]
        [StringLength(8, ErrorMessage = "密碼必須3-8字元", MinimumLength = 3)]
        public string RePassword { get; set; }

        [DisplayName("信箱")]
        [Required]
        [EmailAddress(ErrorMessage = "信箱格式有誤")]
        [StringLength(50)]
        public string Email { get; set; }

        [DisplayName("暱稱")]
        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        [DisplayName("生日")]
        public System.DateTime Birthday { get; set; }

        [DisplayName("創建日期")]
        public System.DateTime CreateTime { get; set; }

        [StringLength(50)]
        public string PicPath { get; set; }
    }
}
